---
- hosts: gss-wks
  become: yes
  become_method: sudo

  roles:
    - { role: common, tags: common }
    - { role: teamviewer, tags: teamviewer }
    - { role: zoiper, tags: zoiper }
    - { role: clamav, tags: clamav }
    - { role: security, tags: security }