---
- name: Download TeamViewer package
  get_url:
    url: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
    dest: "/tmp/teamviewer_amd64.deb"
    force: yes

- name: Install TeamViewer
  apt:
    deb: "/tmp/teamviewer_amd64.deb"
    force: yes

- name: Stop TeamViewer Service
  command: teamviewer daemon stop

- name: Setting TV to only accepting internal connection
  lineinfile:
    dest: /opt/teamviewer/config/global.conf
    line: "{{ item }}"
  with_items:
    - '[int32] EulaAccepted = 1'
    - '[int32] General_DirectLAN = 1'
    - '[int32] LanOnly = 1'

- name: Set Teamviewer start automaticaly
  command: teamviewer daemon enable

- name: Set Teamviewer start
  command: teamviewer daemon start

- name: Set default password
  command: teamviewer passwd Pass4TV