---
- name: Update Grub
  command: update-grub
  
- name: Update Database
  command: dconf update

- name: Reboot System
  shell: sleep 2 && shutdown -r now "Ansible package updates triggered"
  async: 1
  poll: 0
  ignore_errors: true